// Generated by https://quicktype.io

export interface Product {
    createdAt:     Date;
    product:       string;
    points:        number;
    image:         string;
    is_redemption: boolean;
    id:            string;
}
